### ISSUE TITLE
HR

### ISSUE THREAD

**Issue by davedew** [afixia/CKC-Issues#1]
- [x] Timecard tracking overnight employees
- [x] Incomplete indicating on timecards that do have end date
- [x] Can we have dates read as the end of the week instead of the beginning (example on time cards – selector bar says 1/5/2019 (sat.), I would like it to say 1/11/19. One the billing side, it starts at 1/7 (mon.) but is should also be 1/11)? When I am doing payroll and billing I work off of Fridays and seeing the beginning date is confusing, especially when they are starting at different points.
- [x] Timecards -filtering by Active employees, using employee drop down menu, Mee Thao - I click on the Mee Thao link to see which school she works at, when I return to Mee Thao timecard page for last week, now the "acti e employee" isn't being recognized as I can see non active employees,

**Comment by davedew** [comment]
Have initial implementation for the overnight tracking.  Testing on Staging server.

**Comment by ckcmercury** [comment]
timecards -filtering by Active employees, using employee drop down menu, Mee Thao - I click on the Mee Thao link to see which school she works at, when I return to Mee Thao timecard page for last week, now the "acti e employee" isn't being recognized as I can see non active employees, 
![image](https://user-images.githubusercontent.com/46682440/51259592-1b824880-1972-11e9-8f89-23eb684a877a.png)

**Comment by ckcmercury** [comment]
Scott Mueller timecard - according to Scott "skipped a day" = 1/17- trying to add 1/17 time into 1/18 for and I see this:
![image](https://user-images.githubusercontent.com/46682440/51392552-fc62f280-1afa-11e9-9907-ced70270d6c8.png) shows January dates only through 1/17

**Comment by davedew** [comment]
> Scott Mueller timecard - according to Scott "skipped a day" = 1/17- trying to add 1/17 time into 1/18 for and I see this:
> ![image](https://user-images.githubusercontent.com/46682440/51392552-fc62f280-1afa-11e9-9907-ced70270d6c8.png) shows January dates only through 1/17

There is an adjustment for this on the staging server.
