### ISSUE TITLE
Annoucements

### ISSUE THREAD

**Issue by davedew** [afixia/CKC-Issues#11]
- [x] When clicking back to a previously created announcement, the staff list is gone
- [x] Alphabetize employee list

**Comment by cjcrawford** [comment]
- Added ability to remove users / employees / schools
- Added delay to sending the notification if the start date is in the future
- Fixed syncing issue on adding new users / employees / schools

**Comment by davedew** [comment]
I fixed some of the school selection issues, there was a change from gradeId to grade.id.  I deployed on staging and tested an announcements to schools, employees and users.  After creation, leaving the page, then revisiting the announcements, none of the selected users showed under schools, users, or employees.

**Comment by cjcrawford** [comment]
can you make sure when testing you are running:

```bash
redis-cli flushAll
php artisan cache:clear
# IMPORTANT
php artisan queue:work --tries=1
```

**Comment by davedew** [comment]
Confirmed, the selections stick after running the queue:work  Checking this off.
