### ISSUE TITLE
Daily Prep Sheets

### ISSUE THREAD

**Issue by davedew** [afixia/CKC-Issues#3]
- [x] Columns in prep sheets need to be arranged in the sort order of prep category.
- [x] The bag lunches numbers occur in the serving day’s prep sheet. Is it possible to make it occur in the delivery day’s prep sheet instead?

**Comment by ckcmercury** [comment]
Last week, the grade order in prep sheet skewed up.
![image](https://user-images.githubusercontent.com/46682440/51481635-ef900a00-1d59-11e9-8ab5-5e0ff45c1510.png)

**Comment by davedew** [comment]
Just uploaded to Staging server new code to make the daily prep sheets obey the ordering of grades and prep categories.
