### ISSUE TITLE
Schools

### ISSUE THREAD

**Issue by davedew** [afixia/CKC-Issues#4]
- Activity Tracker
  - [x] Activities need to be arranged by descending order of time stamp (most recent on top)
  - [x] Dates are wrong in the tracker
  - [x] Select No Lunch
  - [x] Changes
- Users
  - [ ] Load users isn't consistent.  Seems like a state is sticking from another search?
  - [x] In Schools/Customers list, if we click on a school and view 'Users' tab for that school, we would get the users list of the school. If we click on any user in this list it takes to a blank school edit page and not to the users info page. I think it is a broken link problem
  - [x] After editing a user from the school list, add option to return to that page instead of the full user list.
- Edit
  - [x] Could not delete LADC Annunciation's Room 2
  - [x] Auto add default room or add room validation.  Should not be able to save without a room.
- Menu Relations
  - [x] Make this interface only save by using the save button

**Comment by ckcmercury** [comment]
From a School/Customer page, when we go to a users tab, and click on a user name, it directs to a empty school record page, with no info. Looks like a broken link. Also, after this, if we go to Users list, the list is already filtered for users belonging to that school/customer.

**Comment by davedew** [comment]
> From a School/Customer page, when we go to a users tab, and click on a user name, it directs to a empty school record page, with no info. Looks like a broken link. Also, after this, if we go to Users list, the list is already filtered for users belonging to that school/customer.

For now, try clicking on the refresh button.  I think the search state is setting, but doesn't clear when that page loads.

**Comment by ckcmercury** [comment]
Ref

> 
> 
> > From a School/Customer page, when we go to a users tab, and click on a user name, it directs to a empty school record page, with no info. Looks like a broken link. Also, after this, if we go to Users list, the list is already filtered for users belonging to that school/customer.
> 
> For now, try clicking on the refresh button. I think the search state is setting, but doesn't clear when that page loads.

The refresh button too didnt work. We need to click some other link and come back to Users. Then only it takes off the filter.

**Comment by davedew** [comment]
Ok thanks, I've added this to the top checklist.

**Comment by davedew** [comment]
Just to double check, are you clicking the refresh on the browser on the page/search refresh?

**Comment by ckcmercury** [comment]
> 
> 
> Just to double check, are you clicking the refresh on the browser on the page/search refresh?

No, that must be the mistake, I am clicking the one on the top of the list, thinking that that would clear the selection.

**Comment by davedew** [comment]
No, that's not a mistake.  Just wanted to see which was being clicked to make sure we know where the issue is.

**Comment by ckcmercury** [comment]
Could not delete LADC Annunciation's Room 2. Previously, this client had two rooms, but now only one. If I try to delete it, error pops up. Is this because still room2 has old meal counts entered under it?

**Comment by davedew** [comment]
Ok we will check this out.

**Comment by cjcrawford** [comment]
School adding / saving logic just got a upgrade with fixes to:

- grades
- route
- rooms
- employees

currently on staging server:

[CKC Staging Server: Edit School : Afixia](https://ckc-staging.mercurycreativegroup.com/admin/schools/edit/266/)

**Comment by davedew** [comment]
Confirmed.  I was able to delete LADC's Room 2 locally and accounting still showed the counts for both rooms from back in September.

- Grade editing looks good.
- Editing or clearing a route and saving seems to work as well.
- Adding a room seems to **not** save / stick.
- Employees is good.

**Comment by davedew** [comment]
Adding room looks good now.

**Comment by ckcmercury** [comment]
Activity tracker does not track deletion of meal counts

**Comment by davedew** [comment]
Deletion as in a change from a number to 0 or having the day set to no school?

**Comment by ckcmercury** [comment]
Deletion here would refer to changing counts to 0, for now.
Other than that, the activity tracker would be tracking the following:
 

- Selecting 'No Lunch'

- Changing meal counts

- Changing general properties of a school

I am not sure how much of these are already asked from you.

**Comment by davedew** [comment]
We will check on this.  I know it tracks the initial meal count and general changes to schools currently.  There has been no other asks.  The scope was to just rebuild what the old site had for school activity, but due to the auto saves and the loss of the confirm order button, this works a little differently now.

**Comment by davedew** [comment]
Ok logging for no school and meal count changes has been added to the staging server for review.

**Comment by ckcmercury** [comment]
> 
> 
> Ok logging for no school and meal count changes has been added to the staging server for review.

I have checked this. This works good in both the scenarios.

**Comment by davedew** [comment]
Excellent, thanks!  We'll post this tomorrow morning.

**Comment by ckcmercury** [comment]
Thank you

**Comment by ckcmercury** [comment]
I am sorry. One more question on this. While tracking updated meal counts, can it say 'from 20 to 25'? That There is a already existing count 20 and now updated to 25.
 please dont consider it if it is not a straight forward simple change.

**Comment by davedew** [comment]
Easy enough.  This has been added to the staging server.

**Comment by ckcmercury** [comment]
Works perfect!
