### ISSUE TITLE
General

### ISSUE THREAD

**Issue by davedew** [afixia/CKC-Issues#7]
- [x] The background image in the front screen has lighter color as majority, so it is not supporting the white font in that page.
- [x] Every time, we delete a record from a list, and move to recovery pile, that record is not at the top. We need to surf through the entire list to find it. Just in case, if we accidentally delete an employee and does not know which record, we deleted, we would have a hard time finding it in the recovery list. ---- (Decided to sort the list by descending order of time stamp)
- [x] We don’t have an option to unselect any record, that was selected. Every time, we select a record, the option on the top of the list changes. So, to set it back, we need to unselect the selected record. In a list that runs about five pages, we need to go through all the pages and find which one is selected and unselect it.  (It would be good to have a single option at the top of the list that clears all the filters and all the selection in that list.)
- [x] The email that is received after clicking reset password, has last name first name syntax. Can it be changed to first name last name? (The data is always going to retain the last name, first name format. Only for emailing purposes can it be changed. It would be better if it says, ‘Hey Steve Schnaser’.
- [x] In some places, Calendars start with a Monday and in some places, with Sunday. (In food ordering report, it starts with Monday, but in prep sheets it starts with Sunday). - Prefer them to start on Monday.
- [x] Alphabetical list whenever a large listing is displayed. (Ex. Menu relations for customer, school filter in bulk, breakfast, order report, school list in form builder)
- [x] Prevent user > login as user of admin, root, hr, or financial roles
- [x] Using the reset button doesn't clear the filters right after you add a filter and search.  Only after you reload the page does the reset button work.
- [x] Logging in to an admin with no customer places you in Annunciation's customer portal.
- [x] Apply single value relation sorting on relations such as Inventory > Form Category

**Comment by cjcrawford** [comment]
### Selection Checkbox
- The selection is now scoped to visible data
- The reset button should clear all filters, page, selections and reset the data

![image](https://user-images.githubusercontent.com/21323126/51076826-3424f280-1642-11e9-9cb2-05b99306aacc.png)
